[package]
name = "integration-tests"
version = "0.1.0"
edition = "2018"
publish = false

[[bin]]
name = "test-locator"
path = "locator.rs"

[[test]]
name = "di_diun-tests"
path = "tests/di_diun.rs"

[dependencies]
anyhow = "1"
tempfile = "3"
pretty_assertions = "0.7.2"
tera = "1"
lazy_static = "1.4.0"
openssl = "0.10"
libc = "0.2"
reqwest = "0.11"
tokio = "1.12.0"
